dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
node_js:
- node
env:
  global:
  - ANT_OPTS=-Xmx2048m
  - MYSQL_URL="jdbc:mysql://localhost:3306"
  - POSTGRESQL_URL="jdbc:postgresql://localhost:5432"
  - secure: duj2NzncZG+oNk8ISitO697mne1EzAajvdRjw39yevKTMdMbf6cbMa+beo/3JW8xMbGxMLovfI4zK0Bykoo98VQVJan87tLGTQVmOKGboi0sYvOeun9jXUoT66tQAEtlL48S5nNoHKyF/dRaGgPRPMkfXiPdElAU9FDklm3rwQs=
  - secure: gWPaj/3IUfFU/MGqcB6AkD3MsAlLT9uBP5YZhgCZrgHXYIvyhEH9F+it17b5ibWq+i7boSs9G8HcCRwNdaNrlcN1ONDOVRW1f3syK2+HC947/FfzHE6jnamVbEAZMYr77WgR5eeqLQRl94Q2CRa3eW/6QERM99kt5nbRo3oPT/c=
  - secure: X+82NUnipRkzqBAt4IOgVuW/kDd/m85MEExAxRAxqZ2R6ALCHRMYKpCSv47dW7qnX89EkkN8vEDQ1/5h8bnGY5i1a6b8mMVLS3tkRUtuqW9bL59TzEyVTS6hsWoNNKWL4rzqnDAXTyy4RB881ZGdkTR3nRjrmEZtbfVWLXQCQ+A=
  - secure: Ufv45EFdy9eKEjZ6Za7DAo7X/cAB16G8a9qNj+qvcCOBiZLTjXO8+1Hqj85R5dopZwYvHt0cVaIiPJ+/7z1DeQ9076g5UTdhnK+agPxMW7WPlf9QqXiIDMZbjBsmPEIjp4jF42QDjoxY/tPTsupW45yXkHCeroUAud2zwvDkb1c=
  matrix:
  - TARGET=test-unit
  - TARGET=orbeon-dist
addons:
  postgresql: "9.5"
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  artifacts:
    paths:
    - $(ls build/distrib/* | tr "\n" ":")
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.m2/repository"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt/launchers"
  - "$HOME/node_modules"
before_cache:
# Tricks to avoid unnecessary cache updates
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  #- sudo apt-get update
  - sudo apt-get -y install docker-ce
install:
# From https://docs.travis-ci.com/user/languages/java/: "Because there is no single standard way of installing project dependencies with Ant, you need to
# specify the exact command to run using install". Here we install npm dependencies for Node.js as we need them for integration tests.
- npm install
before_script:
- mkdir /home/travis/.orbeon
# Create `orbeon` user for MySQL and PostgreSQL, and grant privileges
- mysql --protocol=TCP --host=localhost --user root -e "CREATE USER 'orbeon'@'localhost' IDENTIFIED BY '$RDS_PASSWORD'"
- mysql --protocol=TCP --host=localhost --user root -e "GRANT ALL PRIVILEGES ON *.* TO 'orbeon'@'localhost' WITH GRANT OPTION"
- createuser --superuser orbeon
- createdb --owner=orbeon orbeon
# Download other Docker images
- if [ "$TARGET" == "test-unit" ]; then docker pull tomcat:8.0; fi
- if [ "$TARGET" == "test-unit" ]; then docker pull haproxy:1.7; fi
- mkdir -p $HOME/.sbt/launchers/0.13.18/
- curl -L -o $HOME/.sbt/launchers/0.13.18/sbt-launch.jar https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.18/sbt-launch.jar
script:
- "ant $TARGET"